name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          config: ./test/e2e/kind-cluster.yml
          cluster_name: kind-workflow-playground-test
      - name: Deploy
        run: |
          kubectl create ns e2e-test
          kubectl -n e2e-test apply -f ./test/e2e/e2e.yml
      - name: Test
        run: make test
